/**
 * Torchlight — bundled city fallback
 *
 * Copyright (c) 2026 Nives Pandey. All rights reserved.
 * Author: Nives Pandey, Founder & CEO, EagleCortex.
 *
 * PROPRIETARY AND CONFIDENTIAL. Unauthorised copying, distribution, or use of
 * this file, via any medium, is strictly prohibited. See LICENSE.
 */

/**
 * The largest cities worldwide, with verified IANA timezones.
 *
 * Used only when GeoNames cannot be reached. Without it, an outage at a free
 * third-party service would block sign-up entirely — a person could not enter
 * where they were born, so could not get a chart at all.
 *
 * Generated from GeoNames itself rather than typed, so every timezone here is
 * the same value the live service would return. Regenerate by re-running the
 * query in the commit that introduced this file; it is not maintained by hand.
 *
 * 400 cities across 90 countries, ordered by population so a prefix search
 * surfaces the most likely match first.
 */

export interface FallbackCity {
  name: string;
  region: string;
  country: string;
  countryCode: string;
  latitude: number;
  longitude: number;
  timezone: string;
  population: number;
}

export const FALLBACK_CITIES: readonly FallbackCity[] = [
  {
    name: 'Shanghai',
    region: 'Shanghai',
    country: 'China',
    countryCode: 'CN',
    latitude: 31.2222,
    longitude: 121.4581,
    timezone: 'Asia/Shanghai',
    population: 24874500,
  },
  {
    name: 'Beijing',
    region: 'Beijing',
    country: 'China',
    countryCode: 'CN',
    latitude: 39.9075,
    longitude: 116.3972,
    timezone: 'Asia/Shanghai',
    population: 18960744,
  },
  {
    name: 'Shenzhen',
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 22.5455,
    longitude: 114.0683,
    timezone: 'Asia/Shanghai',
    population: 17494398,
  },
  {
    name: 'Guangzhou',
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 23.1167,
    longitude: 113.25,
    timezone: 'Asia/Shanghai',
    population: 16096724,
  },
  {
    name: 'Kinshasa',
    region: 'Kinshasa',
    country: 'DR Congo',
    countryCode: 'CD',
    latitude: -4.3276,
    longitude: 15.3136,
    timezone: 'Africa/Kinshasa',
    population: 16000000,
  },
  {
    name: 'Istanbul',
    region: 'Istanbul',
    country: 'Türkiye',
    countryCode: 'TR',
    latitude: 41.0138,
    longitude: 28.9497,
    timezone: 'Europe/Istanbul',
    population: 15701602,
  },
  {
    name: 'Lagos',
    region: 'Lagos',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 6.4541,
    longitude: 3.3947,
    timezone: 'Africa/Lagos',
    population: 15388000,
  },
  {
    name: 'Ho Chi Minh City',
    region: 'Ho Chi Minh City (HCMC)',
    country: 'Vietnam',
    countryCode: 'VN',
    latitude: 10.823,
    longitude: 106.6296,
    timezone: 'Asia/Ho_Chi_Minh',
    population: 14002598,
  },
  {
    name: 'Chengdu',
    region: 'Sichuan',
    country: 'China',
    countryCode: 'CN',
    latitude: 30.6667,
    longitude: 104.0667,
    timezone: 'Asia/Shanghai',
    population: 13568357,
  },
  {
    name: 'Lahore',
    region: 'Punjab',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 31.558,
    longitude: 74.3507,
    timezone: 'Asia/Karachi',
    population: 13004135,
  },
  {
    name: 'Mumbai',
    region: 'Maharashtra',
    country: 'India',
    countryCode: 'IN',
    latitude: 19.0728,
    longitude: 72.8826,
    timezone: 'Asia/Kolkata',
    population: 12691836,
  },
  {
    name: 'São Paulo',
    region: 'São Paulo',
    country: 'Brazil',
    countryCode: 'BR',
    latitude: -23.5475,
    longitude: -46.6361,
    timezone: 'America/Sao_Paulo',
    population: 12400232,
  },
  {
    name: 'Mexico City',
    region: 'Mexico City',
    country: 'Mexico',
    countryCode: 'MX',
    latitude: 19.4285,
    longitude: -99.1277,
    timezone: 'America/Mexico_City',
    population: 12294193,
  },
  {
    name: 'Karachi',
    region: 'Sindh',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 24.8608,
    longitude: 67.0104,
    timezone: 'Asia/Karachi',
    population: 11624219,
  },
  {
    name: 'Tianjin',
    region: 'Tianjin',
    country: 'China',
    countryCode: 'CN',
    latitude: 39.1422,
    longitude: 117.1767,
    timezone: 'Asia/Shanghai',
    population: 11090314,
  },
  {
    name: 'Delhi',
    region: 'Delhi',
    country: 'India',
    countryCode: 'IN',
    latitude: 28.6519,
    longitude: 77.2315,
    timezone: 'Asia/Kolkata',
    population: 11034555,
  },
  {
    name: 'Wuhan',
    region: 'Hubei',
    country: 'China',
    countryCode: 'CN',
    latitude: 30.5833,
    longitude: 114.2667,
    timezone: 'Asia/Shanghai',
    population: 10392693,
  },
  {
    name: 'Moscow',
    region: 'Moscow',
    country: 'Russia',
    countryCode: 'RU',
    latitude: 55.752,
    longitude: 37.6178,
    timezone: 'Europe/Moscow',
    population: 10381222,
  },
  {
    name: 'Dhaka',
    region: 'Dhaka Division',
    country: 'Bangladesh',
    countryCode: 'BD',
    latitude: 23.7104,
    longitude: 90.4074,
    timezone: 'Asia/Dhaka',
    population: 10356500,
  },
  {
    name: 'Seoul',
    region: 'Seoul',
    country: 'South Korea',
    countryCode: 'KR',
    latitude: 37.566,
    longitude: 126.9784,
    timezone: 'Asia/Seoul',
    population: 10349312,
  },
  {
    name: 'Tokyo',
    region: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 35.6895,
    longitude: 139.6917,
    timezone: 'Asia/Tokyo',
    population: 9733276,
  },
  {
    name: 'Dongguan',
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 23.018,
    longitude: 113.7487,
    timezone: 'Asia/Shanghai',
    population: 9644871,
  },
  {
    name: 'Cairo',
    region: 'Cairo',
    country: 'Egypt',
    countryCode: 'EG',
    latitude: 30.0626,
    longitude: 31.2497,
    timezone: 'Africa/Cairo',
    population: 9606916,
  },
  {
    name: "Xi'an",
    region: 'Shaanxi',
    country: 'China',
    countryCode: 'CN',
    latitude: 34.2583,
    longitude: 108.9286,
    timezone: 'Asia/Shanghai',
    population: 9600000,
  },
  {
    name: 'Johannesburg',
    region: 'Gauteng',
    country: 'South Africa',
    countryCode: 'ZA',
    latitude: -26.2023,
    longitude: 28.0436,
    timezone: 'Africa/Johannesburg',
    population: 9418183,
  },
  {
    name: 'Nanjing',
    region: 'Jiangsu',
    country: 'China',
    countryCode: 'CN',
    latitude: 32.0617,
    longitude: 118.7778,
    timezone: 'Asia/Shanghai',
    population: 9314685,
  },
  {
    name: 'Hangzhou',
    region: 'Zhejiang',
    country: 'China',
    countryCode: 'CN',
    latitude: 30.2936,
    longitude: 120.1614,
    timezone: 'Asia/Shanghai',
    population: 9236032,
  },
  {
    name: 'Foshan',
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 23.0268,
    longitude: 113.1315,
    timezone: 'Asia/Shanghai',
    population: 9042509,
  },
  {
    name: 'London',
    region: 'England',
    country: 'United Kingdom',
    countryCode: 'GB',
    latitude: 51.5085,
    longitude: -0.1257,
    timezone: 'Europe/London',
    population: 8961989,
  },
  {
    name: 'New York',
    region: 'New York',
    country: 'United States',
    countryCode: 'US',
    latitude: 40.7143,
    longitude: -74.006,
    timezone: 'America/New_York',
    population: 8804190,
  },
  {
    name: 'Jakarta',
    region: 'Jakarta',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -6.2146,
    longitude: 106.8451,
    timezone: 'Asia/Jakarta',
    population: 8540121,
  },
  {
    name: 'Bengaluru',
    region: 'Karnataka',
    country: 'India',
    countryCode: 'IN',
    latitude: 12.9719,
    longitude: 77.5937,
    timezone: 'Asia/Kolkata',
    population: 8495492,
  },
  {
    name: 'Hanoi',
    region: 'Hanoi',
    country: 'Vietnam',
    countryCode: 'VN',
    latitude: 21.0245,
    longitude: 105.8412,
    timezone: 'Asia/Bangkok',
    population: 8053663,
  },
  {
    name: 'Taipei',
    region: 'Taiwan',
    country: 'Taiwan',
    countryCode: 'TW',
    latitude: 25.0531,
    longitude: 121.5264,
    timezone: 'Asia/Taipei',
    population: 7871900,
  },
  {
    name: 'Lima',
    region: 'Lima Province',
    country: 'Peru',
    countryCode: 'PE',
    latitude: -12.0432,
    longitude: -77.0282,
    timezone: 'America/Lima',
    population: 7737002,
  },
  {
    name: 'Bogotá',
    region: 'Bogota D.C.',
    country: 'Colombia',
    countryCode: 'CO',
    latitude: 4.6097,
    longitude: -74.0817,
    timezone: 'America/Bogota',
    population: 7674366,
  },
  {
    name: 'Chongqing',
    region: 'Chongqing',
    country: 'China',
    countryCode: 'CN',
    latitude: 29.5603,
    longitude: 106.5577,
    timezone: 'Asia/Shanghai',
    population: 7457599,
  },
  {
    name: 'Hong Kong',
    region: '',
    country: 'Hong Kong',
    countryCode: 'HK',
    latitude: 22.2783,
    longitude: 114.1747,
    timezone: 'Asia/Hong_Kong',
    population: 7396076,
  },
  {
    name: 'Baghdad',
    region: 'Baghdad',
    country: 'Iraq',
    countryCode: 'IQ',
    latitude: 33.3406,
    longitude: 44.4009,
    timezone: 'Asia/Baghdad',
    population: 7216000,
  },
  {
    name: 'Qingdao',
    region: 'Shandong',
    country: 'China',
    countryCode: 'CN',
    latitude: 36.0649,
    longitude: 120.3804,
    timezone: 'Asia/Shanghai',
    population: 7172451,
  },
  {
    name: 'Tehran',
    region: 'Tehran',
    country: 'Iran',
    countryCode: 'IR',
    latitude: 35.6944,
    longitude: 51.4215,
    timezone: 'Asia/Tehran',
    population: 7153309,
  },
  {
    name: 'Shenyang',
    region: 'Liaoning',
    country: 'China',
    countryCode: 'CN',
    latitude: 41.7922,
    longitude: 123.4328,
    timezone: 'Asia/Shanghai',
    population: 7050000,
  },
  {
    name: 'Hyderabad',
    region: 'Telangana',
    country: 'India',
    countryCode: 'IN',
    latitude: 17.384,
    longitude: 78.4564,
    timezone: 'Asia/Kolkata',
    population: 6993262,
  },
  {
    name: 'Rio de Janeiro',
    region: 'Rio de Janeiro',
    country: 'Brazil',
    countryCode: 'BR',
    latitude: -22.9064,
    longitude: -43.1822,
    timezone: 'America/Sao_Paulo',
    population: 6747815,
  },
  {
    name: 'Suzhou',
    region: 'Jiangsu',
    country: 'China',
    countryCode: 'CN',
    latitude: 31.3041,
    longitude: 120.5954,
    timezone: 'Asia/Shanghai',
    population: 6715559,
  },
  {
    name: 'Ahmedabad',
    region: 'Gujarat',
    country: 'India',
    countryCode: 'IN',
    latitude: 23.0258,
    longitude: 72.5873,
    timezone: 'Asia/Kolkata',
    population: 6357693,
  },
  {
    name: 'Abidjan',
    region: 'Abidjan Autonomous District',
    country: 'Ivory Coast',
    countryCode: 'CI',
    latitude: 5.3544,
    longitude: -4.0017,
    timezone: 'Africa/Abidjan',
    population: 6321017,
  },
  {
    name: 'Singapore',
    region: '',
    country: 'Singapore',
    countryCode: 'SG',
    latitude: 1.2897,
    longitude: 103.8501,
    timezone: 'Asia/Singapore',
    population: 5638700,
  },
  {
    name: 'Sydney',
    region: 'New South Wales',
    country: 'Australia',
    countryCode: 'AU',
    latitude: -33.8678,
    longitude: 151.2073,
    timezone: 'Australia/Sydney',
    population: 5557233,
  },
  {
    name: 'Dar es Salaam',
    region: 'Dar es Salaam Region',
    country: 'Tanzania',
    countryCode: 'TZ',
    latitude: -6.8235,
    longitude: 39.2695,
    timezone: 'Africa/Dar_es_Salaam',
    population: 5383728,
  },
  {
    name: 'St Petersburg',
    region: 'St.-Petersburg',
    country: 'Russia',
    countryCode: 'RU',
    latitude: 59.9386,
    longitude: 30.3141,
    timezone: 'Europe/Moscow',
    population: 5351935,
  },
  {
    name: 'Melbourne',
    region: 'Victoria',
    country: 'Australia',
    countryCode: 'AU',
    latitude: -37.814,
    longitude: 144.9633,
    timezone: 'Australia/Melbourne',
    population: 5350705,
  },
  {
    name: 'Alexandria',
    region: 'Alexandria',
    country: 'Egypt',
    countryCode: 'EG',
    latitude: 31.2018,
    longitude: 29.9158,
    timezone: 'Africa/Cairo',
    population: 5263542,
  },
  {
    name: 'Harbin',
    region: 'Heilongjiang',
    country: 'China',
    countryCode: 'CN',
    latitude: 45.75,
    longitude: 126.65,
    timezone: 'Asia/Shanghai',
    population: 5242897,
  },
  {
    name: 'Bangkok',
    region: 'Bangkok',
    country: 'Thailand',
    countryCode: 'TH',
    latitude: 13.754,
    longitude: 100.5014,
    timezone: 'Asia/Bangkok',
    population: 5104476,
  },
  {
    name: 'Hefei',
    region: 'Anhui',
    country: 'China',
    countryCode: 'CN',
    latitude: 31.8639,
    longitude: 117.2808,
    timezone: 'Asia/Shanghai',
    population: 5050000,
  },
  {
    name: 'Dalian',
    region: 'Liaoning',
    country: 'China',
    countryCode: 'CN',
    latitude: 38.9122,
    longitude: 121.6022,
    timezone: 'Asia/Shanghai',
    population: 4913879,
  },
  {
    name: 'Kano',
    region: 'Kano State',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 12.0001,
    longitude: 8.5167,
    timezone: 'Africa/Lagos',
    population: 4910000,
  },
  {
    name: 'Santiago',
    region: 'Santiago Metropolitan',
    country: 'Chile',
    countryCode: 'CL',
    latitude: -33.4569,
    longitude: -70.6483,
    timezone: 'America/Santiago',
    population: 4837295,
  },
  {
    name: 'Cape Town',
    region: 'Western Cape',
    country: 'South Africa',
    countryCode: 'ZA',
    latitude: -33.9258,
    longitude: 18.4232,
    timezone: 'Africa/Johannesburg',
    population: 4772846,
  },
  {
    name: 'Peshawar',
    region: 'Khyber Pakhtunkhwa',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 34.008,
    longitude: 71.5785,
    timezone: 'Asia/Karachi',
    population: 4758762,
  },
  {
    name: 'Changchun',
    region: 'Jilin',
    country: 'China',
    countryCode: 'CN',
    latitude: 43.88,
    longitude: 125.3228,
    timezone: 'Asia/Shanghai',
    population: 4714996,
  },
  {
    name: 'Jeddah',
    region: 'Mecca Region',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    latitude: 21.4901,
    longitude: 39.1862,
    timezone: 'Asia/Riyadh',
    population: 4697000,
  },
  {
    name: 'Chennai',
    region: 'Tamil Nadu',
    country: 'India',
    countryCode: 'IN',
    latitude: 13.0878,
    longitude: 80.2785,
    timezone: 'Asia/Kolkata',
    population: 4681087,
  },
  {
    name: 'Kolkata',
    region: 'West Bengal',
    country: 'India',
    countryCode: 'IN',
    latitude: 22.5626,
    longitude: 88.363,
    timezone: 'Asia/Kolkata',
    population: 4631392,
  },
  {
    name: 'Xiamen',
    region: 'Fujian',
    country: 'China',
    countryCode: 'CN',
    latitude: 24.4798,
    longitude: 118.0819,
    timezone: 'Asia/Shanghai',
    population: 4617251,
  },
  {
    name: 'Surat',
    region: 'Gujarat',
    country: 'India',
    countryCode: 'IN',
    latitude: 21.1959,
    longitude: 72.8302,
    timezone: 'Asia/Kolkata',
    population: 4591246,
  },
  {
    name: 'Yangon',
    region: 'Yangon',
    country: 'Myanmar',
    countryCode: 'MM',
    latitude: 16.8053,
    longitude: 96.1561,
    timezone: 'Asia/Yangon',
    population: 4477638,
  },
  {
    name: "Bao'an",
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 22.5521,
    longitude: 113.8829,
    timezone: 'Asia/Shanghai',
    population: 4476554,
  },
  {
    name: 'Kabul',
    region: 'Kabul',
    country: 'Afghanistan',
    countryCode: 'AF',
    latitude: 34.5281,
    longitude: 69.1723,
    timezone: 'Asia/Kabul',
    population: 4434550,
  },
  {
    name: 'Nairobi',
    region: 'Nairobi County',
    country: 'Kenya',
    countryCode: 'KE',
    latitude: -1.2833,
    longitude: 36.8167,
    timezone: 'Africa/Nairobi',
    population: 4397073,
  },
  {
    name: 'Wuxi',
    region: 'Jiangsu',
    country: 'China',
    countryCode: 'CN',
    latitude: 31.5689,
    longitude: 120.2886,
    timezone: 'Asia/Shanghai',
    population: 4396835,
  },
  {
    name: 'Giza',
    region: 'Giza',
    country: 'Egypt',
    countryCode: 'EG',
    latitude: 30.0094,
    longitude: 31.2086,
    timezone: 'Africa/Cairo',
    population: 4367343,
  },
  {
    name: 'Jinan',
    region: 'Shandong',
    country: 'China',
    countryCode: 'CN',
    latitude: 36.6683,
    longitude: 116.9972,
    timezone: 'Asia/Shanghai',
    population: 4335989,
  },
  {
    name: 'Taiyuan',
    region: 'Shanxi',
    country: 'China',
    countryCode: 'CN',
    latitude: 37.8694,
    longitude: 112.5603,
    timezone: 'Asia/Shanghai',
    population: 4303673,
  },
  {
    name: 'Zhengzhou',
    region: 'Henan',
    country: 'China',
    countryCode: 'CN',
    latitude: 34.7578,
    longitude: 113.6486,
    timezone: 'Asia/Shanghai',
    population: 4253913,
  },
  {
    name: 'Bamako',
    region: 'Bamako',
    country: 'Mali',
    countryCode: 'ML',
    latitude: 12.6091,
    longitude: -7.9752,
    timezone: 'Africa/Bamako',
    population: 4227569,
  },
  {
    name: 'Riyadh',
    region: 'Riyadh Region',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    latitude: 24.6877,
    longitude: 46.7219,
    timezone: 'Asia/Riyadh',
    population: 4205961,
  },
  {
    name: 'New Taipei',
    region: 'Taipei',
    country: 'Taiwan',
    countryCode: 'TW',
    latitude: 25.062,
    longitude: 121.457,
    timezone: 'Asia/Taipei',
    population: 4004367,
  },
  {
    name: 'New Territories',
    region: '',
    country: 'Hong Kong',
    countryCode: 'HK',
    latitude: 22.4244,
    longitude: 114.111,
    timezone: 'Asia/Hong_Kong',
    population: 3984077,
  },
  {
    name: 'Shijiazhuang',
    region: 'Hebei',
    country: 'China',
    countryCode: 'CN',
    latitude: 38.0414,
    longitude: 114.4786,
    timezone: 'Asia/Shanghai',
    population: 3938513,
  },
  {
    name: 'Chittagong',
    region: 'Chittagong',
    country: 'Bangladesh',
    countryCode: 'BD',
    latitude: 22.3384,
    longitude: 91.8317,
    timezone: 'Asia/Dhaka',
    population: 3920222,
  },
  {
    name: 'Addis Ababa',
    region: 'Addis Ababa',
    country: 'Ethiopia',
    countryCode: 'ET',
    latitude: 9.025,
    longitude: 38.7469,
    timezone: 'Africa/Addis_Ababa',
    population: 3860000,
  },
  {
    name: 'Kunming',
    region: 'Yunnan',
    country: 'China',
    countryCode: 'CN',
    latitude: 25.0389,
    longitude: 102.7183,
    timezone: 'Asia/Shanghai',
    population: 3855346,
  },
  {
    name: 'Zhongshan',
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 22.5231,
    longitude: 113.3791,
    timezone: 'Asia/Shanghai',
    population: 3841873,
  },
  {
    name: 'Nanning',
    region: 'Guangxi',
    country: 'China',
    countryCode: 'CN',
    latitude: 22.8167,
    longitude: 108.3167,
    timezone: 'Asia/Shanghai',
    population: 3839800,
  },
  {
    name: 'Shantou',
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 23.3549,
    longitude: 116.6788,
    timezone: 'Asia/Shanghai',
    population: 3838900,
  },
  {
    name: 'Los Angeles',
    region: 'California',
    country: 'United States',
    countryCode: 'US',
    latitude: 34.0522,
    longitude: -118.2437,
    timezone: 'America/Los_Angeles',
    population: 3820914,
  },
  {
    name: 'Faisalabad',
    region: 'Punjab',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 31.4155,
    longitude: 73.0897,
    timezone: 'Asia/Karachi',
    population: 3800193,
  },
  {
    name: 'Dubai',
    region: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    latitude: 25.0772,
    longitude: 55.3093,
    timezone: 'Asia/Dubai',
    population: 3790000,
  },
  {
    name: 'Yokohama',
    region: 'Kanagawa',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 35.4333,
    longitude: 139.65,
    timezone: 'Asia/Tokyo',
    population: 3777491,
  },
  {
    name: 'Fuzhou',
    region: 'Fujian',
    country: 'China',
    countryCode: 'CN',
    latitude: 26.0614,
    longitude: 119.3061,
    timezone: 'Asia/Shanghai',
    population: 3740000,
  },
  {
    name: 'Ningbo',
    region: 'Zhejiang',
    country: 'China',
    countryCode: 'CN',
    latitude: 29.8782,
    longitude: 121.5494,
    timezone: 'Asia/Shanghai',
    population: 3731203,
  },
  {
    name: 'Casablanca',
    region: 'Casablanca-Settat',
    country: 'Morocco',
    countryCode: 'MA',
    latitude: 33.5883,
    longitude: -7.6114,
    timezone: 'Africa/Casablanca',
    population: 3665954,
  },
  {
    name: 'Ibadan',
    region: 'Oyo State',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 7.3776,
    longitude: 3.9059,
    timezone: 'Africa/Lagos',
    population: 3649000,
  },
  {
    name: 'Pujiang',
    region: 'Zhejiang',
    country: 'China',
    countryCode: 'CN',
    latitude: 29.4568,
    longitude: 119.8887,
    timezone: 'Asia/Shanghai',
    population: 3590000,
  },
  {
    name: 'Ankara',
    region: 'Ankara',
    country: 'Türkiye',
    countryCode: 'TR',
    latitude: 39.9199,
    longitude: 32.8543,
    timezone: 'Europe/Istanbul',
    population: 3517182,
  },
  {
    name: 'Shiyan',
    region: 'Hubei',
    country: 'China',
    countryCode: 'CN',
    latitude: 32.6475,
    longitude: 110.7781,
    timezone: 'Asia/Shanghai',
    population: 3460000,
  },
  {
    name: 'Berlin',
    region: 'State of Berlin',
    country: 'Germany',
    countryCode: 'DE',
    latitude: 52.5244,
    longitude: 13.4105,
    timezone: 'Europe/Berlin',
    population: 3426354,
  },
  {
    name: 'Tangshan',
    region: 'Hebei',
    country: 'China',
    countryCode: 'CN',
    latitude: 39.6438,
    longitude: 118.1832,
    timezone: 'Asia/Shanghai',
    population: 3372102,
  },
  {
    name: 'Rawalpindi',
    region: 'Punjab',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 33.5973,
    longitude: 73.0479,
    timezone: 'Asia/Karachi',
    population: 3357612,
  },
  {
    name: 'Lüliang',
    region: 'Shanxi',
    country: 'China',
    countryCode: 'CN',
    latitude: 37.5192,
    longitude: 111.1444,
    timezone: 'Asia/Shanghai',
    population: 3346500,
  },
  {
    name: 'Busan',
    region: 'Busan',
    country: 'South Korea',
    countryCode: 'KR',
    latitude: 35.1017,
    longitude: 129.03,
    timezone: 'Asia/Seoul',
    population: 3343903,
  },
  {
    name: 'Durban',
    region: 'KwaZulu-Natal',
    country: 'South Africa',
    countryCode: 'ZA',
    latitude: -29.8579,
    longitude: 31.0292,
    timezone: 'Africa/Johannesburg',
    population: 3338026,
  },
  {
    name: 'Changzhou',
    region: 'Jiangsu',
    country: 'China',
    countryCode: 'CN',
    latitude: 31.7736,
    longitude: 119.954,
    timezone: 'Asia/Shanghai',
    population: 3290918,
  },
  {
    name: 'Madrid',
    region: 'Madrid',
    country: 'Spain',
    countryCode: 'ES',
    latitude: 40.4165,
    longitude: -3.7026,
    timezone: 'Europe/Madrid',
    population: 3255944,
  },
  {
    name: 'Pyongyang',
    region: 'Pyongyang',
    country: 'North Korea',
    countryCode: 'KP',
    latitude: 39.0339,
    longitude: 125.7543,
    timezone: 'Asia/Pyongyang',
    population: 3222000,
  },
  {
    name: 'Zibo',
    region: 'Shandong',
    country: 'China',
    countryCode: 'CN',
    latitude: 36.7906,
    longitude: 118.0633,
    timezone: 'Asia/Shanghai',
    population: 3129228,
  },
  {
    name: 'Pune',
    region: 'Maharashtra',
    country: 'India',
    countryCode: 'IN',
    latitude: 18.5196,
    longitude: 73.8554,
    timezone: 'Asia/Kolkata',
    population: 3124458,
  },
  {
    name: 'Bursa',
    region: 'Bursa Province',
    country: 'Türkiye',
    countryCode: 'TR',
    latitude: 40.1956,
    longitude: 29.0601,
    timezone: 'Europe/Istanbul',
    population: 3101833,
  },
  {
    name: 'Changsha',
    region: 'Hunan',
    country: 'China',
    countryCode: 'CN',
    latitude: 28.1987,
    longitude: 112.9709,
    timezone: 'Asia/Shanghai',
    population: 3093980,
  },
  {
    name: 'Quezon City',
    region: 'National Capital Region',
    country: 'Philippines',
    countryCode: 'PH',
    latitude: 14.6488,
    longitude: 121.0509,
    timezone: 'Asia/Manila',
    population: 3084270,
  },
  {
    name: 'Jaipur',
    region: 'Rajasthan',
    country: 'India',
    countryCode: 'IN',
    latitude: 26.9196,
    longitude: 75.7878,
    timezone: 'Asia/Kolkata',
    population: 3046163,
  },
  {
    name: 'Incheon',
    region: 'Incheon',
    country: 'South Korea',
    countryCode: 'KR',
    latitude: 37.4565,
    longitude: 126.7052,
    timezone: 'Asia/Seoul',
    population: 3039450,
  },
  {
    name: 'Guiyang',
    region: 'Guizhou',
    country: 'China',
    countryCode: 'CN',
    latitude: 26.5833,
    longitude: 106.7167,
    timezone: 'Asia/Shanghai',
    population: 3037159,
  },
  {
    name: 'Ürümqi',
    region: 'Xinjiang',
    country: 'China',
    countryCode: 'CN',
    latitude: 43.801,
    longitude: 87.6005,
    timezone: 'Asia/Urumqi',
    population: 3029372,
  },
  {
    name: 'Lanzhou',
    region: 'Gansu',
    country: 'China',
    countryCode: 'CN',
    latitude: 36.057,
    longitude: 103.8399,
    timezone: 'Asia/Shanghai',
    population: 3000000,
  },
  {
    name: 'Caracas',
    region: 'Distrito Federal',
    country: 'Venezuela',
    countryCode: 'VE',
    latitude: 10.488,
    longitude: -66.8792,
    timezone: 'America/Caracas',
    population: 3000000,
  },
  {
    name: 'Izmir',
    region: 'İzmir Province',
    country: 'Türkiye',
    countryCode: 'TR',
    latitude: 38.4127,
    longitude: 27.1384,
    timezone: 'Europe/Istanbul',
    population: 2938292,
  },
  {
    name: 'Huizhou',
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 23.1115,
    longitude: 114.4152,
    timezone: 'Asia/Shanghai',
    population: 2900113,
  },
  {
    name: 'Buenos Aires',
    region: 'Buenos Aires F.D.',
    country: 'Argentina',
    countryCode: 'AR',
    latitude: -34.6131,
    longitude: -58.3772,
    timezone: 'America/Argentina/Buenos_Aires',
    population: 2891082,
  },
  {
    name: 'Surabaya',
    region: 'East Java',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -7.2492,
    longitude: 112.7508,
    timezone: 'Asia/Jakarta',
    population: 2874314,
  },
  {
    name: 'Haikou',
    region: 'Hainan',
    country: 'China',
    countryCode: 'CN',
    latitude: 20.0342,
    longitude: 110.3465,
    timezone: 'Asia/Shanghai',
    population: 2873358,
  },
  {
    name: 'Taichung',
    region: 'Taiwan',
    country: 'Taiwan',
    countryCode: 'TW',
    latitude: 24.1469,
    longitude: 120.6839,
    timezone: 'Asia/Taipei',
    population: 2850285,
  },
  {
    name: 'Kanpur',
    region: 'Uttar Pradesh',
    country: 'India',
    countryCode: 'IN',
    latitude: 26.4652,
    longitude: 80.3498,
    timezone: 'Asia/Kolkata',
    population: 2823249,
  },
  {
    name: 'Kyiv',
    region: 'Kyiv City',
    country: 'Ukraine',
    countryCode: 'UA',
    latitude: 50.4547,
    longitude: 30.5238,
    timezone: 'Europe/Kyiv',
    population: 2797553,
  },
  {
    name: 'Toronto',
    region: 'Ontario',
    country: 'Canada',
    countryCode: 'CA',
    latitude: 43.7064,
    longitude: -79.3986,
    timezone: 'America/Toronto',
    population: 2794356,
  },
  {
    name: 'Quito',
    region: 'Pichincha',
    country: 'Ecuador',
    countryCode: 'EC',
    latitude: -0.2298,
    longitude: -78.525,
    timezone: 'America/Guayaquil',
    population: 2781641,
  },
  {
    name: 'Brisbane',
    region: 'Queensland',
    country: 'Australia',
    countryCode: 'AU',
    latitude: -27.4679,
    longitude: 153.0281,
    timezone: 'Australia/Brisbane',
    population: 2780063,
  },
  {
    name: 'Luanda',
    region: 'Luanda',
    country: 'Angola',
    countryCode: 'AO',
    latitude: -8.8368,
    longitude: 13.2343,
    timezone: 'Africa/Luanda',
    population: 2776168,
  },
  {
    name: 'Osaka',
    region: 'Osaka',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 34.6938,
    longitude: 135.5011,
    timezone: 'Asia/Tokyo',
    population: 2753862,
  },
  {
    name: 'Linyi',
    region: 'Shandong',
    country: 'China',
    countryCode: 'CN',
    latitude: 35.0631,
    longitude: 118.3428,
    timezone: 'Asia/Shanghai',
    population: 2743843,
  },
  {
    name: 'Baoding',
    region: 'Hebei',
    country: 'China',
    countryCode: 'CN',
    latitude: 38.8729,
    longitude: 115.4625,
    timezone: 'Asia/Shanghai',
    population: 2739887,
  },
  {
    name: 'Kaohsiung',
    region: 'Kaohsiung',
    country: 'Taiwan',
    countryCode: 'TW',
    latitude: 22.6163,
    longitude: 120.3133,
    timezone: 'Asia/Taipei',
    population: 2737660,
  },
  {
    name: 'Brooklyn',
    region: 'New York',
    country: 'United States',
    countryCode: 'US',
    latitude: 40.6501,
    longitude: -73.9496,
    timezone: 'America/New_York',
    population: 2736074,
  },
  {
    name: 'Guayaquil',
    region: 'Guayas',
    country: 'Ecuador',
    countryCode: 'EC',
    latitude: -2.1962,
    longitude: -79.8862,
    timezone: 'America/Guayaquil',
    population: 2723665,
  },
  {
    name: 'Belo Horizonte',
    region: 'Minas Gerais',
    country: 'Brazil',
    countryCode: 'BR',
    latitude: -19.9208,
    longitude: -43.9378,
    timezone: 'America/Sao_Paulo',
    population: 2721564,
  },
  {
    name: 'Salvador',
    region: 'Bahia',
    country: 'Brazil',
    countryCode: 'BR',
    latitude: -12.9756,
    longitude: -38.491,
    timezone: 'America/Bahia',
    population: 2711840,
  },
  {
    name: 'Abuja',
    region: 'FCT',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 9.0579,
    longitude: 7.4951,
    timezone: 'Africa/Lagos',
    population: 2690000,
  },
  {
    name: 'Gazipur',
    region: 'Dhaka Division',
    country: 'Bangladesh',
    countryCode: 'BD',
    latitude: 23.9984,
    longitude: 90.4223,
    timezone: 'Asia/Dhaka',
    population: 2674697,
  },
  {
    name: 'Chicago',
    region: 'Illinois',
    country: 'United States',
    countryCode: 'US',
    latitude: 41.85,
    longitude: -87.65,
    timezone: 'America/Chicago',
    population: 2664452,
  },
  {
    name: 'Wenzhou',
    region: 'Zhejiang',
    country: 'China',
    countryCode: 'CN',
    latitude: 27.9994,
    longitude: 120.6668,
    timezone: 'Asia/Shanghai',
    population: 2650000,
  },
  {
    name: 'Dakar',
    region: 'Dakar',
    country: 'Senegal',
    countryCode: 'SN',
    latitude: 14.6937,
    longitude: -17.4441,
    timezone: 'Africa/Dakar',
    population: 2646503,
  },
  {
    name: 'Haiphong',
    region: 'Hai Phong',
    country: 'Vietnam',
    countryCode: 'VN',
    latitude: 20.8648,
    longitude: 106.6834,
    timezone: 'Asia/Bangkok',
    population: 2625200,
  },
  {
    name: 'Yunfu',
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 22.9279,
    longitude: 112.0381,
    timezone: 'Asia/Shanghai',
    population: 2612800,
  },
  {
    name: 'Navi Mumbai',
    region: 'Maharashtra',
    country: 'India',
    countryCode: 'IN',
    latitude: 19.0368,
    longitude: 73.0158,
    timezone: 'Asia/Kolkata',
    population: 2600000,
  },
  {
    name: 'Mogadishu',
    region: 'Banaadir',
    country: 'Somalia',
    countryCode: 'SO',
    latitude: 2.0371,
    longitude: 45.3438,
    timezone: 'Africa/Mogadishu',
    population: 2587183,
  },
  {
    name: 'Bekasi',
    region: 'West Java',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -6.2349,
    longitude: 106.9896,
    timezone: 'Asia/Jakarta',
    population: 2564940,
  },
  {
    name: 'Kumasi',
    region: 'Ashanti',
    country: 'Ghana',
    countryCode: 'GH',
    latitude: 6.6885,
    longitude: -1.6244,
    timezone: 'Africa/Accra',
    population: 2544530,
  },
  {
    name: 'Gujranwala',
    region: 'Punjab',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 32.1557,
    longitude: 74.187,
    timezone: 'Asia/Karachi',
    population: 2511118,
  },
  {
    name: "Huai'an",
    region: 'Jiangsu',
    country: 'China',
    countryCode: 'CN',
    latitude: 33.5886,
    longitude: 119.0192,
    timezone: 'Asia/Shanghai',
    population: 2494013,
  },
  {
    name: 'Lucknow',
    region: 'Uttar Pradesh',
    country: 'India',
    countryCode: 'IN',
    latitude: 26.8393,
    longitude: 80.9231,
    timezone: 'Asia/Kolkata',
    population: 2472011,
  },
  {
    name: 'Bandung',
    region: 'West Java',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -6.9222,
    longitude: 107.6069,
    timezone: 'Asia/Jakarta',
    population: 2444160,
  },
  {
    name: 'Medan',
    region: 'North Sumatra',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: 3.5833,
    longitude: 98.6667,
    timezone: 'Asia/Jakarta',
    population: 2435252,
  },
  {
    name: 'Ouagadougou',
    region: 'Centre',
    country: 'Burkina Faso',
    countryCode: 'BF',
    latitude: 12.3657,
    longitude: -1.5339,
    timezone: 'Africa/Ouagadougou',
    population: 2415266,
  },
  {
    name: 'Nagpur',
    region: 'Maharashtra',
    country: 'India',
    countryCode: 'IN',
    latitude: 21.1463,
    longitude: 79.0849,
    timezone: 'Asia/Kolkata',
    population: 2405665,
  },
  {
    name: 'Fortaleza',
    region: 'Ceará',
    country: 'Brazil',
    countryCode: 'BR',
    latitude: -3.7172,
    longitude: -38.5431,
    timezone: 'America/Fortaleza',
    population: 2400000,
  },
  {
    name: 'Cali',
    region: 'Valle del Cauca Department',
    country: 'Colombia',
    countryCode: 'CO',
    latitude: 3.4305,
    longitude: -76.5199,
    timezone: 'America/Bogota',
    population: 2392877,
  },
  {
    name: 'Daegu',
    region: 'Daegu',
    country: 'South Korea',
    countryCode: 'KR',
    latitude: 35.8703,
    longitude: 128.5911,
    timezone: 'Asia/Seoul',
    population: 2365523,
  },
  {
    name: 'Algiers',
    region: 'Algiers',
    country: 'Algeria',
    countryCode: 'DZ',
    latitude: 36.7323,
    longitude: 3.0875,
    timezone: 'Africa/Algiers',
    population: 2364230,
  },
  {
    name: 'Nanchang',
    region: 'Jiangxi',
    country: 'China',
    countryCode: 'CN',
    latitude: 28.684,
    longitude: 115.8531,
    timezone: 'Asia/Shanghai',
    population: 2357839,
  },
  {
    name: 'Hohhot',
    region: 'Inner Mongolia',
    country: 'China',
    countryCode: 'CN',
    latitude: 40.8106,
    longitude: 111.6522,
    timezone: 'Asia/Shanghai',
    population: 2350000,
  },
  {
    name: 'Nagoya',
    region: 'Aichi',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 35.1815,
    longitude: 136.9064,
    timezone: 'Asia/Tokyo',
    population: 2332176,
  },
  {
    name: 'Rome',
    region: 'Lazio',
    country: 'Italy',
    countryCode: 'IT',
    latitude: 41.8919,
    longitude: 12.5113,
    timezone: 'Europe/Rome',
    population: 2318895,
  },
  {
    name: 'Queens County',
    region: 'New York',
    country: 'United States',
    countryCode: 'US',
    latitude: 40.6815,
    longitude: -73.8365,
    timezone: 'America/New_York',
    population: 2316841,
  },
  {
    name: 'Houston',
    region: 'Texas',
    country: 'United States',
    countryCode: 'US',
    latitude: 29.7633,
    longitude: -95.3633,
    timezone: 'America/Chicago',
    population: 2314157,
  },
  {
    name: 'Perth',
    region: 'Western Australia',
    country: 'Australia',
    countryCode: 'AU',
    latitude: -31.9522,
    longitude: 115.8614,
    timezone: 'Australia/Perth',
    population: 2309338,
  },
  {
    name: 'Mashhad',
    region: 'Razavi Khorasan',
    country: 'Iran',
    countryCode: 'IR',
    latitude: 36.2981,
    longitude: 59.6057,
    timezone: 'Asia/Tehran',
    population: 2307177,
  },
  {
    name: 'Shaoxing',
    region: 'Zhejiang',
    country: 'China',
    countryCode: 'CN',
    latitude: 30.0024,
    longitude: 120.5786,
    timezone: 'Asia/Shanghai',
    population: 2300000,
  },
  {
    name: 'Nantong',
    region: 'Jiangsu',
    country: 'China',
    countryCode: 'CN',
    latitude: 32.0303,
    longitude: 120.8747,
    timezone: 'Asia/Shanghai',
    population: 2273326,
  },
  {
    name: 'Kowloon',
    region: '',
    country: 'Hong Kong',
    countryCode: 'HK',
    latitude: 22.3167,
    longitude: 114.1833,
    timezone: 'Asia/Hong_Kong',
    population: 2232339,
  },
  {
    name: 'Yantai',
    region: 'Shandong',
    country: 'China',
    countryCode: 'CN',
    latitude: 37.4765,
    longitude: 121.4408,
    timezone: 'Asia/Shanghai',
    population: 2227733,
  },
  {
    name: 'Lubumbashi',
    region: 'Haut-Katanga',
    country: 'DR Congo',
    countryCode: 'CD',
    latitude: -11.6609,
    longitude: 27.4794,
    timezone: 'Africa/Lubumbashi',
    population: 2221925,
  },
  {
    name: 'Manaus',
    region: 'Amazonas',
    country: 'Brazil',
    countryCode: 'BR',
    latitude: -3.1019,
    longitude: -60.025,
    timezone: 'America/Manaus',
    population: 2219580,
  },
  {
    name: 'Lusaka',
    region: 'Lusaka Province',
    country: 'Zambia',
    countryCode: 'ZM',
    latitude: -15.4067,
    longitude: 28.2871,
    timezone: 'Africa/Lusaka',
    population: 2212301,
  },
  {
    name: 'Brasília',
    region: 'Federal District',
    country: 'Brazil',
    countryCode: 'BR',
    latitude: -15.7797,
    longitude: -47.9297,
    timezone: 'America/Sao_Paulo',
    population: 2207718,
  },
  {
    name: 'Zhuhai',
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 22.2769,
    longitude: 113.5678,
    timezone: 'Asia/Shanghai',
    population: 2207090,
  },
  {
    name: 'Santo Domingo',
    region: 'Nacional',
    country: 'Dominican Republic',
    countryCode: 'DO',
    latitude: 18.4719,
    longitude: -69.8923,
    timezone: 'America/Santo_Domingo',
    population: 2201941,
  },
  {
    name: 'Lomé',
    region: 'Maritime',
    country: 'Togo',
    countryCode: 'TG',
    latitude: 6.1287,
    longitude: 1.2215,
    timezone: 'Africa/Lome',
    population: 2188376,
  },
  {
    name: 'Multan',
    region: 'Punjab',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 30.1968,
    longitude: 71.4782,
    timezone: 'Asia/Karachi',
    population: 2169915,
  },
  {
    name: 'Havana',
    region: 'Havana',
    country: 'Cuba',
    countryCode: 'CU',
    latitude: 23.133,
    longitude: -82.383,
    timezone: 'America/Havana',
    population: 2163824,
  },
  {
    name: 'Baotou',
    region: 'Inner Mongolia',
    country: 'China',
    countryCode: 'CN',
    latitude: 40.6516,
    longitude: 109.8439,
    timezone: 'Asia/Shanghai',
    population: 2150000,
  },
  {
    name: 'Depok',
    region: 'West Java',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -6.4,
    longitude: 106.8186,
    timezone: 'Asia/Jakarta',
    population: 2145400,
  },
  {
    name: 'Paris',
    region: 'Île-de-France',
    country: 'France',
    countryCode: 'FR',
    latitude: 48.8534,
    longitude: 2.3488,
    timezone: 'Europe/Paris',
    population: 2138551,
  },
  {
    name: 'Coimbatore',
    region: 'Tamil Nadu',
    country: 'India',
    countryCode: 'IN',
    latitude: 11.0055,
    longitude: 76.9661,
    timezone: 'Asia/Kolkata',
    population: 2136916,
  },
  {
    name: 'Gaziantep',
    region: 'Gaziantep',
    country: 'Türkiye',
    countryCode: 'TR',
    latitude: 37.0594,
    longitude: 37.3825,
    timezone: 'Europe/Istanbul',
    population: 2130432,
  },
  {
    name: 'Qingyang',
    region: 'Gansu',
    country: 'China',
    countryCode: 'CN',
    latitude: 35.7098,
    longitude: 107.6445,
    timezone: 'Asia/Shanghai',
    population: 2125400,
  },
  {
    name: 'Port Harcourt',
    region: 'Rivers State',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 4.7774,
    longitude: 7.0134,
    timezone: 'Africa/Lagos',
    population: 2120000,
  },
  {
    name: 'Pretoria',
    region: 'Gauteng',
    country: 'South Africa',
    countryCode: 'ZA',
    latitude: -25.7449,
    longitude: 28.1878,
    timezone: 'Africa/Johannesburg',
    population: 2112693,
  },
  {
    name: 'Córdoba',
    region: 'Cordoba',
    country: 'Argentina',
    countryCode: 'AR',
    latitude: -31.4065,
    longitude: -64.1885,
    timezone: 'America/Argentina/Cordoba',
    population: 2106734,
  },
  {
    name: 'Mbuji-Mayi',
    region: 'East Kasai',
    country: 'DR Congo',
    countryCode: 'CD',
    latitude: -6.136,
    longitude: 23.5898,
    timezone: 'Africa/Lubumbashi',
    population: 2101332,
  },
  {
    name: 'Aleppo',
    region: 'Aleppo',
    country: 'Syria',
    countryCode: 'SY',
    latitude: 36.2012,
    longitude: 37.1612,
    timezone: 'Asia/Damascus',
    population: 2098210,
  },
  {
    name: 'Kunshan',
    region: 'Jiangsu',
    country: 'China',
    countryCode: 'CN',
    latitude: 31.3776,
    longitude: 120.9543,
    timezone: 'Asia/Shanghai',
    population: 2092496,
  },
  {
    name: 'Al Mawşil al Jadīdah',
    region: 'Nineveh',
    country: 'Iraq',
    countryCode: 'IQ',
    latitude: 36.3327,
    longitude: 43.1056,
    timezone: 'Asia/Baghdad',
    population: 2065597,
  },
  {
    name: 'Weifang',
    region: 'Shandong',
    country: 'China',
    countryCode: 'CN',
    latitude: 36.71,
    longitude: 119.1019,
    timezone: 'Asia/Shanghai',
    population: 2044028,
  },
  {
    name: 'Zunyi',
    region: 'Guizhou',
    country: 'China',
    countryCode: 'CN',
    latitude: 27.6867,
    longitude: 106.9072,
    timezone: 'Asia/Shanghai',
    population: 2037775,
  },
  {
    name: 'Al Başrah al Qadīmah',
    region: 'Basra',
    country: 'Iraq',
    countryCode: 'IQ',
    latitude: 30.5032,
    longitude: 47.8151,
    timezone: 'Asia/Baghdad',
    population: 2015483,
  },
  {
    name: 'La Paz',
    region: 'La Paz Department',
    country: 'Bolivia',
    countryCode: 'BO',
    latitude: -16.5,
    longitude: -68.15,
    timezone: 'America/La_Paz',
    population: 2004652,
  },
  {
    name: 'Lianyungang',
    region: 'Jiangsu',
    country: 'China',
    countryCode: 'CN',
    latitude: 34.5984,
    longitude: 119.2156,
    timezone: 'Asia/Shanghai',
    population: 2001009,
  },
  {
    name: 'Medellín',
    region: 'Antioquia',
    country: 'Colombia',
    countryCode: 'CO',
    latitude: 6.245,
    longitude: -75.5715,
    timezone: 'America/Bogota',
    population: 1999979,
  },
  {
    name: 'Indore',
    region: 'Madhya Pradesh',
    country: 'India',
    countryCode: 'IN',
    latitude: 22.7179,
    longitude: 75.8333,
    timezone: 'Asia/Kolkata',
    population: 1994397,
  },
  {
    name: 'Brazzaville',
    region: 'Brazzaville',
    country: 'Congo Republic',
    countryCode: 'CG',
    latitude: -4.2661,
    longitude: 15.2832,
    timezone: 'Africa/Brazzaville',
    population: 1982000,
  },
  {
    name: 'Tashkent',
    region: 'Tashkent',
    country: 'Uzbekistan',
    countryCode: 'UZ',
    latitude: 41.2647,
    longitude: 69.2163,
    timezone: 'Asia/Tashkent',
    population: 1978028,
  },
  {
    name: 'Ganzhou',
    region: 'Jiangxi',
    country: 'China',
    countryCode: 'CN',
    latitude: 25.8466,
    longitude: 114.9326,
    timezone: 'Asia/Shanghai',
    population: 1977253,
  },
  {
    name: 'Almaty',
    region: 'Almaty',
    country: 'Kazakhstan',
    countryCode: 'KZ',
    latitude: 43.2525,
    longitude: 76.9115,
    timezone: 'Asia/Almaty',
    population: 1977011,
  },
  {
    name: 'Khartoum',
    region: 'Khartoum',
    country: 'Sudan',
    countryCode: 'SD',
    latitude: 15.5518,
    longitude: 32.5324,
    timezone: 'Africa/Khartoum',
    population: 1974647,
  },
  {
    name: 'Sapporo',
    region: 'Hokkaido',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 43.0667,
    longitude: 141.35,
    timezone: 'Asia/Tokyo',
    population: 1973832,
  },
  {
    name: 'Accra',
    region: 'Greater Accra',
    country: 'Ghana',
    countryCode: 'GH',
    latitude: 5.556,
    longitude: -0.1969,
    timezone: 'Africa/Accra',
    population: 1963264,
  },
  {
    name: 'Curitiba',
    region: 'Paraná',
    country: 'Brazil',
    countryCode: 'BR',
    latitude: -25.4278,
    longitude: -49.2731,
    timezone: 'America/Sao_Paulo',
    population: 1948626,
  },
  {
    name: 'Ordos',
    region: 'Inner Mongolia',
    country: 'China',
    countryCode: 'CN',
    latitude: 39.6086,
    longitude: 109.7816,
    timezone: 'Asia/Shanghai',
    population: 1940653,
  },
  {
    name: 'Sanaa',
    region: 'Amanat Alasimah',
    country: 'Yemen',
    countryCode: 'YE',
    latitude: 15.3545,
    longitude: 44.2065,
    timezone: 'Asia/Aden',
    population: 1937451,
  },
  {
    name: 'Conakry',
    region: 'Conakry',
    country: 'Guinea',
    countryCode: 'GN',
    latitude: 9.538,
    longitude: -13.6773,
    timezone: 'Africa/Conakry',
    population: 1928389,
  },
  {
    name: 'Tijuana',
    region: 'Baja California',
    country: 'Mexico',
    countryCode: 'MX',
    latitude: 32.5027,
    longitude: -117.0037,
    timezone: 'America/Tijuana',
    population: 1922523,
  },
  {
    name: 'Hyderābād',
    region: 'Sindh',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 25.3969,
    longitude: 68.3772,
    timezone: 'Asia/Karachi',
    population: 1921275,
  },
  {
    name: 'Beirut',
    region: 'Beyrouth',
    country: 'Lebanon',
    countryCode: 'LB',
    latitude: 33.8933,
    longitude: 35.5016,
    timezone: 'Asia/Beirut',
    population: 1916100,
  },
  {
    name: 'Tangerang',
    region: 'Banten',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -6.1781,
    longitude: 106.63,
    timezone: 'Asia/Jakarta',
    population: 1912679,
  },
  {
    name: 'Jieyang',
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 23.5418,
    longitude: 116.3658,
    timezone: 'Asia/Shanghai',
    population: 1899394,
  },
  {
    name: 'Jilin',
    region: 'Jilin',
    country: 'China',
    countryCode: 'CN',
    latitude: 43.8465,
    longitude: 126.5608,
    timezone: 'Asia/Shanghai',
    population: 1895865,
  },
  {
    name: 'Bucharest',
    region: 'București',
    country: 'Romania',
    countryCode: 'RO',
    latitude: 44.4323,
    longitude: 26.1063,
    timezone: 'Europe/Bucharest',
    population: 1877155,
  },
  {
    name: 'Camayenne',
    region: 'Conakry',
    country: 'Guinea',
    countryCode: 'GN',
    latitude: 9.535,
    longitude: -13.6878,
    timezone: 'Africa/Conakry',
    population: 1871242,
  },
  {
    name: 'Kakamega',
    region: 'Kakamega County',
    country: 'Kenya',
    countryCode: 'KE',
    latitude: 0.2842,
    longitude: 34.7523,
    timezone: 'Africa/Nairobi',
    population: 1867579,
  },
  {
    name: 'Nanchong',
    region: 'Sichuan',
    country: 'China',
    countryCode: 'CN',
    latitude: 30.7951,
    longitude: 106.0847,
    timezone: 'Asia/Shanghai',
    population: 1858875,
  },
  {
    name: 'Tainan',
    region: 'Taiwan',
    country: 'Taiwan',
    countryCode: 'TW',
    latitude: 22.9908,
    longitude: 120.2133,
    timezone: 'Asia/Taipei',
    population: 1856642,
  },
  {
    name: 'Kaduna',
    region: 'Kaduna State',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 10.5264,
    longitude: 7.4388,
    timezone: 'Africa/Lagos',
    population: 1850000,
  },
  {
    name: 'Datong',
    region: 'Shanxi',
    country: 'China',
    countryCode: 'CN',
    latitude: 40.0936,
    longitude: 113.2914,
    timezone: 'Asia/Shanghai',
    population: 1850000,
  },
  {
    name: 'Omdurman',
    region: 'Khartoum',
    country: 'Sudan',
    countryCode: 'SD',
    latitude: 15.6445,
    longitude: 32.4777,
    timezone: 'Africa/Khartoum',
    population: 1849659,
  },
  {
    name: 'Davao City',
    region: 'Davao Region',
    country: 'Philippines',
    countryCode: 'PH',
    latitude: 7.0731,
    longitude: 125.6128,
    timezone: 'Asia/Manila',
    population: 1848947,
  },
  {
    name: 'Hamburg',
    region: 'Hamburg',
    country: 'Germany',
    countryCode: 'DE',
    latitude: 53.5507,
    longitude: 9.993,
    timezone: 'Europe/Berlin',
    population: 1845229,
  },
  {
    name: 'Thane',
    region: 'Maharashtra',
    country: 'India',
    countryCode: 'IN',
    latitude: 19.197,
    longitude: 72.9635,
    timezone: 'Asia/Kolkata',
    population: 1841488,
  },
  {
    name: 'Iztapalapa',
    region: 'Mexico City',
    country: 'Mexico',
    countryCode: 'MX',
    latitude: 19.3553,
    longitude: -99.0622,
    timezone: 'America/Mexico_City',
    population: 1835486,
  },
  {
    name: 'Santa Cruz',
    region: 'Santa Cruz Department',
    country: 'Bolivia',
    countryCode: 'BO',
    latitude: -17.7863,
    longitude: -63.1812,
    timezone: 'America/La_Paz',
    population: 1831434,
  },
  {
    name: 'Vadodara',
    region: 'Gujarat',
    country: 'India',
    countryCode: 'IN',
    latitude: 22.2994,
    longitude: 73.2081,
    timezone: 'Asia/Kolkata',
    population: 1822221,
  },
  {
    name: 'Adana',
    region: 'Adana',
    country: 'Türkiye',
    countryCode: 'TR',
    latitude: 36.9862,
    longitude: 35.3253,
    timezone: 'Europe/Istanbul',
    population: 1816750,
  },
  {
    name: 'Nanyang',
    region: 'Henan',
    country: 'China',
    countryCode: 'CN',
    latitude: 33.0052,
    longitude: 112.5466,
    timezone: 'Asia/Shanghai',
    population: 1811812,
  },
  {
    name: 'Abu Dhabi',
    region: 'Abu Dhabi',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    latitude: 24.4512,
    longitude: 54.397,
    timezone: 'Asia/Dubai',
    population: 1807000,
  },
  {
    name: 'Sharjah',
    region: 'Sharjah',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    latitude: 25.3342,
    longitude: 55.4122,
    timezone: 'Asia/Dubai',
    population: 1800000,
  },
  {
    name: 'Bhopal',
    region: 'Madhya Pradesh',
    country: 'India',
    countryCode: 'IN',
    latitude: 23.2547,
    longitude: 77.4029,
    timezone: 'Asia/Kolkata',
    population: 1798218,
  },
  {
    name: 'Jiangmen',
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 22.5833,
    longitude: 113.0833,
    timezone: 'Asia/Shanghai',
    population: 1795459,
  },
  {
    name: 'Diyarbakır',
    region: 'Diyarbakır Province',
    country: 'Türkiye',
    countryCode: 'TR',
    latitude: 37.9136,
    longitude: 40.2172,
    timezone: 'Europe/Istanbul',
    population: 1791373,
  },
  {
    name: 'Benin City',
    region: 'Edo State',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 6.3381,
    longitude: 5.6258,
    timezone: 'Africa/Lagos',
    population: 1782000,
  },
  {
    name: 'Jiangyin',
    region: 'Jiangsu',
    country: 'China',
    countryCode: 'CN',
    latitude: 31.911,
    longitude: 120.263,
    timezone: 'Asia/Shanghai',
    population: 1779515,
  },
  {
    name: 'Fuyang',
    region: 'Anhui',
    country: 'China',
    countryCode: 'CN',
    latitude: 32.9,
    longitude: 115.8167,
    timezone: 'Asia/Shanghai',
    population: 1768947,
  },
  {
    name: 'Montreal',
    region: 'Quebec',
    country: 'Canada',
    countryCode: 'CA',
    latitude: 45.5088,
    longitude: -73.5878,
    timezone: 'America/Toronto',
    population: 1762949,
  },
  {
    name: 'Bayan Nur',
    region: 'Inner Mongolia',
    country: 'China',
    countryCode: 'CN',
    latitude: 40.7414,
    longitude: 107.386,
    timezone: 'Asia/Shanghai',
    population: 1760000,
  },
  {
    name: 'Maracaibo',
    region: 'Zulia',
    country: 'Venezuela',
    countryCode: 'VE',
    latitude: 10.6423,
    longitude: -71.6109,
    timezone: 'America/Caracas',
    population: 1752602,
  },
  {
    name: 'Chaozhou',
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 23.654,
    longitude: 116.6226,
    timezone: 'Asia/Shanghai',
    population: 1750945,
  },
  {
    name: 'Minsk',
    region: 'Minsk City',
    country: 'Belarus',
    countryCode: 'BY',
    latitude: 53.9002,
    longitude: 27.5665,
    timezone: 'Europe/Minsk',
    population: 1742124,
  },
  {
    name: 'Budapest',
    region: 'Budapest',
    country: 'Hungary',
    countryCode: 'HU',
    latitude: 47.4984,
    longitude: 19.0404,
    timezone: 'Europe/Budapest',
    population: 1741041,
  },
  {
    name: 'Qingyuan',
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 23.7,
    longitude: 113.0333,
    timezone: 'Asia/Shanghai',
    population: 1738424,
  },
  {
    name: 'Tai’an',
    region: 'Shandong',
    country: 'China',
    countryCode: 'CN',
    latitude: 36.1853,
    longitude: 117.12,
    timezone: 'Asia/Shanghai',
    population: 1735425,
  },
  {
    name: 'Rasapūdipalem',
    region: 'Andhra Pradesh',
    country: 'India',
    countryCode: 'IN',
    latitude: 17.7331,
    longitude: 83.3162,
    timezone: 'Asia/Kolkata',
    population: 1728128,
  },
  {
    name: 'Pimpri-Chinchwad',
    region: 'Maharashtra',
    country: 'India',
    countryCode: 'IN',
    latitude: 18.6187,
    longitude: 73.8037,
    timezone: 'Asia/Kolkata',
    population: 1727692,
  },
  {
    name: 'Caloocan',
    region: 'National Capital Region',
    country: 'Philippines',
    countryCode: 'PH',
    latitude: 14.6495,
    longitude: 120.9679,
    timezone: 'Asia/Manila',
    population: 1712945,
  },
  {
    name: 'Warsaw',
    region: 'Mazovia',
    country: 'Poland',
    countryCode: 'PL',
    latitude: 52.2298,
    longitude: 21.0118,
    timezone: 'Europe/Warsaw',
    population: 1702139,
  },
  {
    name: 'Soweto',
    region: 'Gauteng',
    country: 'South Africa',
    countryCode: 'ZA',
    latitude: -26.2678,
    longitude: 27.8585,
    timezone: 'Africa/Johannesburg',
    population: 1695047,
  },
  {
    name: 'Puebla City',
    region: 'Puebla',
    country: 'Mexico',
    countryCode: 'MX',
    latitude: 19.0478,
    longitude: -98.2072,
    timezone: 'America/Mexico_City',
    population: 1692181,
  },
  {
    name: 'Vienna',
    region: 'Vienna',
    country: 'Austria',
    countryCode: 'AT',
    latitude: 48.2085,
    longitude: 16.3721,
    timezone: 'Europe/Vienna',
    population: 1691468,
  },
  {
    name: 'Barcelona',
    region: 'Catalonia',
    country: 'Spain',
    countryCode: 'ES',
    latitude: 41.3888,
    longitude: 2.159,
    timezone: 'Europe/Madrid',
    population: 1686208,
  },
  {
    name: 'Patna',
    region: 'Bihar',
    country: 'India',
    countryCode: 'IN',
    latitude: 25.5941,
    longitude: 85.1356,
    timezone: 'Asia/Kolkata',
    population: 1684297,
  },
  {
    name: 'Mosul',
    region: 'Nineveh',
    country: 'Iraq',
    countryCode: 'IQ',
    latitude: 36.335,
    longitude: 43.1189,
    timezone: 'Asia/Baghdad',
    population: 1683000,
  },
  {
    name: 'Kallakurichi',
    region: 'Tamil Nadu',
    country: 'India',
    countryCode: 'IN',
    latitude: 11.7338,
    longitude: 78.9592,
    timezone: 'Asia/Kolkata',
    population: 1682687,
  },
  {
    name: 'Kampala',
    region: 'Central Region',
    country: 'Uganda',
    countryCode: 'UG',
    latitude: 0.3163,
    longitude: 32.5822,
    timezone: 'Africa/Kampala',
    population: 1680600,
  },
  {
    name: 'Xining',
    region: 'Qinghai',
    country: 'China',
    countryCode: 'CN',
    latitude: 36.6255,
    longitude: 101.7574,
    timezone: 'Asia/Shanghai',
    population: 1677177,
  },
  {
    name: 'Changshu',
    region: 'Jiangsu',
    country: 'China',
    countryCode: 'CN',
    latitude: 31.6461,
    longitude: 120.7422,
    timezone: 'Asia/Shanghai',
    population: 1677050,
  },
  {
    name: 'Palembang',
    region: 'South Sumatra',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -2.9167,
    longitude: 104.7458,
    timezone: 'Asia/Jakarta',
    population: 1668848,
  },
  {
    name: 'Huainan',
    region: 'Anhui',
    country: 'China',
    countryCode: 'CN',
    latitude: 32.6264,
    longitude: 116.9969,
    timezone: 'Asia/Shanghai',
    population: 1666826,
  },
  {
    name: 'Rabat',
    region: 'Rabat-Salé-Kénitra',
    country: 'Morocco',
    countryCode: 'MA',
    latitude: 34.0132,
    longitude: -6.8326,
    timezone: 'Africa/Casablanca',
    population: 1655753,
  },
  {
    name: 'Semarang',
    region: 'Central Java',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -6.9931,
    longitude: 110.4208,
    timezone: 'Asia/Jakarta',
    population: 1653524,
  },
  {
    name: 'Recife',
    region: 'Pernambuco',
    country: 'Brazil',
    countryCode: 'BR',
    latitude: -8.0539,
    longitude: -34.8811,
    timezone: 'America/Recife',
    population: 1653461,
  },
  {
    name: 'Phoenix',
    region: 'Arizona',
    country: 'United States',
    countryCode: 'US',
    latitude: 33.4484,
    longitude: -112.074,
    timezone: 'America/Phoenix',
    population: 1650070,
  },
  {
    name: 'Suzhou',
    region: 'Anhui',
    country: 'China',
    countryCode: 'CN',
    latitude: 33.6361,
    longitude: 116.9789,
    timezone: 'Asia/Shanghai',
    population: 1647642,
  },
  {
    name: 'Ecatepec',
    region: 'México',
    country: 'Mexico',
    countryCode: 'MX',
    latitude: 19.6049,
    longitude: -99.0606,
    timezone: 'America/Mexico_City',
    population: 1645352,
  },
  {
    name: "Lu'an",
    region: 'Anhui',
    country: 'China',
    countryCode: 'CN',
    latitude: 31.7356,
    longitude: 116.5169,
    timezone: 'Asia/Shanghai',
    population: 1644344,
  },
  {
    name: 'Valencia',
    region: 'Carabobo',
    country: 'Venezuela',
    countryCode: 'VE',
    latitude: 10.1615,
    longitude: -68.0004,
    timezone: 'America/Caracas',
    population: 1619470,
  },
  {
    name: 'Ludhiana',
    region: 'Punjab',
    country: 'India',
    countryCode: 'IN',
    latitude: 30.912,
    longitude: 75.8538,
    timezone: 'Asia/Kolkata',
    population: 1618879,
  },
  {
    name: 'Yancheng',
    region: 'Jiangsu',
    country: 'China',
    countryCode: 'CN',
    latitude: 33.3575,
    longitude: 120.1573,
    timezone: 'Asia/Shanghai',
    population: 1615717,
  },
  {
    name: 'Novosibirsk',
    region: 'Novosibirsk Oblast',
    country: 'Russia',
    countryCode: 'RU',
    latitude: 55.0226,
    longitude: 82.9317,
    timezone: 'Asia/Novosibirsk',
    population: 1612833,
  },
  {
    name: 'Erbil',
    region: 'Erbil',
    country: 'Iraq',
    countryCode: 'IQ',
    latitude: 36.1912,
    longitude: 44.0094,
    timezone: 'Asia/Baghdad',
    population: 1612700,
  },
  {
    name: 'Fukuoka',
    region: 'Fukuoka',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 33.6,
    longitude: 130.4167,
    timezone: 'Asia/Tokyo',
    population: 1612392,
  },
  {
    name: 'Taizhou',
    region: 'Jiangsu',
    country: 'China',
    countryCode: 'CN',
    latitude: 32.4907,
    longitude: 119.9081,
    timezone: 'Asia/Shanghai',
    population: 1607108,
  },
  {
    name: 'Daqing',
    region: 'Heilongjiang',
    country: 'China',
    countryCode: 'CN',
    latitude: 46.5833,
    longitude: 125,
    timezone: 'Asia/Shanghai',
    population: 1604027,
  },
  {
    name: 'Manila',
    region: 'National Capital Region',
    country: 'Philippines',
    countryCode: 'PH',
    latitude: 14.6042,
    longitude: 120.9822,
    timezone: 'Asia/Manila',
    population: 1600000,
  },
  {
    name: 'Wuhu',
    region: 'Anhui',
    country: 'China',
    countryCode: 'CN',
    latitude: 31.3526,
    longitude: 118.4295,
    timezone: 'Asia/Shanghai',
    population: 1598165,
  },
  {
    name: 'Querétaro City',
    region: 'Querétaro',
    country: 'Mexico',
    countryCode: 'MX',
    latitude: 20.5881,
    longitude: -100.3881,
    timezone: 'America/Mexico_City',
    population: 1594212,
  },
  {
    name: 'Dazhou',
    region: 'Sichuan',
    country: 'China',
    countryCode: 'CN',
    latitude: 31.2106,
    longitude: 107.4631,
    timezone: 'Asia/Shanghai',
    population: 1589435,
  },
  {
    name: 'Yangzhou',
    region: 'Jiangsu',
    country: 'China',
    countryCode: 'CN',
    latitude: 32.3972,
    longitude: 119.4358,
    timezone: 'Asia/Shanghai',
    population: 1584237,
  },
  {
    name: 'León',
    region: 'Guanajuato',
    country: 'Mexico',
    countryCode: 'MX',
    latitude: 21.1291,
    longitude: -101.6737,
    timezone: 'America/Mexico_City',
    population: 1579803,
  },
  {
    name: 'Mecca',
    region: 'Mecca Region',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    latitude: 21.4266,
    longitude: 39.8256,
    timezone: 'Asia/Riyadh',
    population: 1578722,
  },
  {
    name: 'Philadelphia',
    region: 'Pennsylvania',
    country: 'United States',
    countryCode: 'US',
    latitude: 39.9524,
    longitude: -75.1636,
    timezone: 'America/New_York',
    population: 1573916,
  },
  {
    name: 'Phnom Penh',
    region: 'Phnom Penh',
    country: 'Cambodia',
    countryCode: 'KH',
    latitude: 11.5625,
    longitude: 104.916,
    timezone: 'Asia/Phnom_Penh',
    population: 1573544,
  },
  {
    name: 'Guilin',
    region: 'Guangxi',
    country: 'China',
    countryCode: 'CN',
    latitude: 25.2802,
    longitude: 110.2964,
    timezone: 'Asia/Shanghai',
    population: 1572300,
  },
  {
    name: 'Damascus',
    region: 'Damascus Governorate',
    country: 'Syria',
    countryCode: 'SY',
    latitude: 33.5102,
    longitude: 36.2913,
    timezone: 'Asia/Damascus',
    population: 1569394,
  },
  {
    name: 'Quetta',
    region: 'Balochistan',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 30.1841,
    longitude: 67.0014,
    timezone: 'Asia/Karachi',
    population: 1565546,
  },
  {
    name: 'Zhaoqing',
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 23.0489,
    longitude: 112.4609,
    timezone: 'Asia/Shanghai',
    population: 1553109,
  },
  {
    name: 'Onitsha',
    region: 'Anambra',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 6.1498,
    longitude: 6.7857,
    timezone: 'Africa/Lagos',
    population: 1553000,
  },
  {
    name: 'Mianyang',
    region: 'Sichuan',
    country: 'China',
    countryCode: 'CN',
    latitude: 31.4678,
    longitude: 104.6817,
    timezone: 'Asia/Shanghai',
    population: 1550000,
  },
  {
    name: 'Isfahan',
    region: 'Isfahan',
    country: 'Iran',
    countryCode: 'IR',
    latitude: 32.6525,
    longitude: 51.6746,
    timezone: 'Asia/Tehran',
    population: 1547164,
  },
  {
    name: 'Wanzhou',
    region: 'Chongqing',
    country: 'China',
    countryCode: 'CN',
    latitude: 30.7645,
    longitude: 108.3959,
    timezone: 'Asia/Shanghai',
    population: 1545900,
  },
  {
    name: 'Harare',
    region: 'Harare',
    country: 'Zimbabwe',
    countryCode: 'ZW',
    latitude: -17.8277,
    longitude: 31.0534,
    timezone: 'Africa/Harare',
    population: 1542813,
  },
  {
    name: 'Monrovia',
    region: 'Montserrado County',
    country: 'Liberia',
    countryCode: 'LR',
    latitude: 6.3005,
    longitude: -10.7969,
    timezone: 'Africa/Monrovia',
    population: 1542549,
  },
  {
    name: 'Putian',
    region: 'Fujian',
    country: 'China',
    countryCode: 'CN',
    latitude: 25.4394,
    longitude: 119.0103,
    timezone: 'Asia/Shanghai',
    population: 1539389,
  },
  {
    name: 'Kawasaki',
    region: 'Kanagawa',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 35.5206,
    longitude: 139.7172,
    timezone: 'Asia/Tokyo',
    population: 1538262,
  },
  {
    name: 'Shangqiu',
    region: 'Henan',
    country: 'China',
    countryCode: 'CN',
    latitude: 34.45,
    longitude: 115.65,
    timezone: 'Asia/Shanghai',
    population: 1536392,
  },
  {
    name: 'Goiânia',
    region: 'Goiás',
    country: 'Brazil',
    countryCode: 'BR',
    latitude: -16.6786,
    longitude: -49.2539,
    timezone: 'America/Sao_Paulo',
    population: 1536097,
  },
  {
    name: 'Auckland',
    region: 'Auckland',
    country: 'New Zealand',
    countryCode: 'NZ',
    latitude: -36.8485,
    longitude: 174.7635,
    timezone: 'Pacific/Auckland',
    population: 1530500,
  },
  {
    name: 'San Antonio',
    region: 'Texas',
    country: 'United States',
    countryCode: 'US',
    latitude: 29.4241,
    longitude: -98.4936,
    timezone: 'America/Chicago',
    population: 1526656,
  },
  {
    name: 'Kobe',
    region: 'Hyōgo',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 34.6913,
    longitude: 135.183,
    timezone: 'Asia/Tokyo',
    population: 1525152,
  },
  {
    name: 'Stockholm',
    region: 'Stockholm',
    country: 'Sweden',
    countryCode: 'SE',
    latitude: 59.3294,
    longitude: 18.0687,
    timezone: 'Europe/Stockholm',
    population: 1515017,
  },
  {
    name: 'Ciudad Juárez',
    region: 'Chihuahua',
    country: 'Mexico',
    countryCode: 'MX',
    latitude: 31.7202,
    longitude: -106.4608,
    timezone: 'America/Ciudad_Juarez',
    population: 1512450,
  },
  {
    name: 'Can Tho',
    region: 'Can Tho City',
    country: 'Vietnam',
    countryCode: 'VN',
    latitude: 10.0371,
    longitude: 105.7883,
    timezone: 'Asia/Ho_Chi_Minh',
    population: 1507187,
  },
  {
    name: 'Khulna',
    region: 'Khulna Division',
    country: 'Bangladesh',
    countryCode: 'BD',
    latitude: 22.8098,
    longitude: 89.5644,
    timezone: 'Asia/Dhaka',
    population: 1500689,
  },
  {
    name: 'Belém',
    region: 'Pará',
    country: 'Brazil',
    countryCode: 'BR',
    latitude: -1.4558,
    longitude: -48.5044,
    timezone: 'America/Belem',
    population: 1499641,
  },
  {
    name: 'Yekaterinburg',
    region: 'Sverdlovsk Oblast',
    country: 'Russia',
    countryCode: 'RU',
    latitude: 56.8573,
    longitude: 60.6153,
    timezone: 'Asia/Yekaterinburg',
    population: 1495066,
  },
  {
    name: 'Porto Alegre',
    region: 'Rio Grande do Sul',
    country: 'Brazil',
    countryCode: 'BR',
    latitude: -30.0328,
    longitude: -51.2302,
    timezone: 'America/Sao_Paulo',
    population: 1488252,
  },
  {
    name: 'Yinchuan',
    region: 'Ningxia',
    country: 'China',
    countryCode: 'CN',
    latitude: 38.4681,
    longitude: 106.2731,
    timezone: 'Asia/Shanghai',
    population: 1487579,
  },
  {
    name: 'Manhattan',
    region: 'New York',
    country: 'United States',
    countryCode: 'US',
    latitude: 40.7834,
    longitude: -73.9663,
    timezone: 'America/New_York',
    population: 1487536,
  },
  {
    name: 'Nashik',
    region: 'Maharashtra',
    country: 'India',
    countryCode: 'IN',
    latitude: 19.9973,
    longitude: 73.791,
    timezone: 'Asia/Kolkata',
    population: 1486053,
  },
  {
    name: 'Taizhou',
    region: 'Zhejiang',
    country: 'China',
    countryCode: 'CN',
    latitude: 28.6627,
    longitude: 121.4331,
    timezone: 'Asia/Shanghai',
    population: 1485502,
  },
  {
    name: 'Asunción',
    region: 'Asunción',
    country: 'Paraguay',
    countryCode: 'PY',
    latitude: -25.2865,
    longitude: -57.647,
    timezone: 'America/Asuncion',
    population: 1482200,
  },
  {
    name: 'Yiwu',
    region: 'Zhejiang',
    country: 'China',
    countryCode: 'CN',
    latitude: 29.3151,
    longitude: 120.0768,
    timezone: 'Asia/Shanghai',
    population: 1481384,
  },
  {
    name: 'Zapopan',
    region: 'Jalisco',
    country: 'Mexico',
    countryCode: 'MX',
    latitude: 20.7211,
    longitude: -103.3874,
    timezone: 'America/Mexico_City',
    population: 1476491,
  },
  {
    name: 'Daejeon',
    region: 'Daejeon',
    country: 'South Korea',
    countryCode: 'KR',
    latitude: 36.3491,
    longitude: 127.3849,
    timezone: 'Asia/Seoul',
    population: 1470336,
  },
  {
    name: 'Adelaide',
    region: 'South Australia',
    country: 'Australia',
    countryCode: 'AU',
    latitude: -34.9287,
    longitude: 138.5986,
    timezone: 'Australia/Adelaide',
    population: 1469163,
  },
  {
    name: 'Quanzhou',
    region: 'Fujian',
    country: 'China',
    countryCode: 'CN',
    latitude: 24.9139,
    longitude: 118.5858,
    timezone: 'Asia/Shanghai',
    population: 1469157,
  },
  {
    name: 'Madurai',
    region: 'Tamil Nadu',
    country: 'India',
    countryCode: 'IN',
    latitude: 9.919,
    longitude: 78.1195,
    timezone: 'Asia/Kolkata',
    population: 1465625,
  },
  {
    name: 'Jinhua',
    region: 'Zhejiang',
    country: 'China',
    countryCode: 'CN',
    latitude: 29.1068,
    longitude: 119.6442,
    timezone: 'Asia/Shanghai',
    population: 1463990,
  },
  {
    name: 'Kyoto',
    region: 'Kyoto',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 35.0211,
    longitude: 135.7538,
    timezone: 'Asia/Tokyo',
    population: 1463723,
  },
  {
    name: 'Cixi',
    region: 'Zhejiang',
    country: 'China',
    countryCode: 'CN',
    latitude: 30.1764,
    longitude: 121.2457,
    timezone: 'Asia/Shanghai',
    population: 1457510,
  },
  {
    name: 'Changde',
    region: 'Hunan',
    country: 'China',
    countryCode: 'CN',
    latitude: 29.0321,
    longitude: 111.6984,
    timezone: 'Asia/Shanghai',
    population: 1457419,
  },
  {
    name: 'Kuala Lumpur',
    region: 'Kuala Lumpur',
    country: 'Malaysia',
    countryCode: 'MY',
    latitude: 3.1412,
    longitude: 101.6865,
    timezone: 'Asia/Kuala_Lumpur',
    population: 1453975,
  },
  {
    name: 'Kaifeng',
    region: 'Henan',
    country: 'China',
    countryCode: 'CN',
    latitude: 34.7986,
    longitude: 114.3074,
    timezone: 'Asia/Shanghai',
    population: 1451741,
  },
  {
    name: 'Anshan',
    region: 'Liaoning',
    country: 'China',
    countryCode: 'CN',
    latitude: 41.1236,
    longitude: 122.99,
    timezone: 'Asia/Shanghai',
    population: 1450000,
  },
  {
    name: 'Karaj',
    region: 'Alborz Province',
    country: 'Iran',
    countryCode: 'IR',
    latitude: 35.8327,
    longitude: 50.9915,
    timezone: 'Asia/Tehran',
    population: 1448075,
  },
  {
    name: 'Kathmandu',
    region: 'Bagmati Province',
    country: 'Nepal',
    countryCode: 'NP',
    latitude: 27.7017,
    longitude: 85.3206,
    timezone: 'Asia/Kathmandu',
    population: 1442271,
  },
  {
    name: 'Baoji',
    region: 'Shaanxi',
    country: 'China',
    countryCode: 'CN',
    latitude: 34.3678,
    longitude: 107.237,
    timezone: 'Asia/Shanghai',
    population: 1437802,
  },
  {
    name: 'Suqian',
    region: 'Jiangsu',
    country: 'China',
    countryCode: 'CN',
    latitude: 33.9492,
    longitude: 118.2958,
    timezone: 'Asia/Shanghai',
    population: 1437685,
  },
  {
    name: 'Liuchow',
    region: 'Guangxi',
    country: 'China',
    countryCode: 'CN',
    latitude: 24.324,
    longitude: 109.407,
    timezone: 'Asia/Shanghai',
    population: 1436599,
  },
  {
    name: 'Tirunelveli',
    region: 'Tamil Nadu',
    country: 'India',
    countryCode: 'IN',
    latitude: 8.7274,
    longitude: 77.6838,
    timezone: 'Asia/Kolkata',
    population: 1435844,
  },
  {
    name: 'Kayseri',
    region: 'Kayseri',
    country: 'Türkiye',
    countryCode: 'TR',
    latitude: 38.7322,
    longitude: 35.4853,
    timezone: 'Europe/Istanbul',
    population: 1434357,
  },
  {
    name: 'Kharkiv',
    region: 'Kharkivs’ka Oblast’',
    country: 'Ukraine',
    countryCode: 'UA',
    latitude: 49.9818,
    longitude: 36.2548,
    timezone: 'Europe/Kyiv',
    population: 1433886,
  },
  {
    name: 'Konya',
    region: 'Konya',
    country: 'Türkiye',
    countryCode: 'TR',
    latitude: 37.8713,
    longitude: 32.4846,
    timezone: 'Europe/Istanbul',
    population: 1433861,
  },
  {
    name: 'Zhangjiagang',
    region: 'Jiangsu',
    country: 'China',
    countryCode: 'CN',
    latitude: 31.865,
    longitude: 120.5389,
    timezone: 'Asia/Shanghai',
    population: 1432044,
  },
  {
    name: 'Agra',
    region: 'Uttar Pradesh',
    country: 'India',
    countryCode: 'IN',
    latitude: 27.1833,
    longitude: 78.0167,
    timezone: 'Asia/Kolkata',
    population: 1430055,
  },
  {
    name: 'Tabriz',
    region: 'East Azerbaijan',
    country: 'Iran',
    countryCode: 'IR',
    latitude: 38.08,
    longitude: 46.2919,
    timezone: 'Asia/Tehran',
    population: 1424641,
  },
  {
    name: 'Makassar',
    region: 'South Sulawesi',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -5.1486,
    longitude: 119.4319,
    timezone: 'Asia/Makassar',
    population: 1423877,
  },
  {
    name: 'Jinjiang',
    region: 'Fujian',
    country: 'China',
    countryCode: 'CN',
    latitude: 24.8198,
    longitude: 118.5742,
    timezone: 'Asia/Shanghai',
    population: 1416151,
  },
  {
    name: 'Faridabad',
    region: 'Haryana',
    country: 'India',
    countryCode: 'IN',
    latitude: 28.4112,
    longitude: 77.3132,
    timezone: 'Asia/Kolkata',
    population: 1414050,
  },
  {
    name: 'Bozhou',
    region: 'Anhui',
    country: 'China',
    countryCode: 'CN',
    latitude: 33.8772,
    longitude: 115.7703,
    timezone: 'Asia/Shanghai',
    population: 1409436,
  },
  {
    name: 'Qujing',
    region: 'Yunnan',
    country: 'China',
    countryCode: 'CN',
    latitude: 25.4833,
    longitude: 103.7833,
    timezone: 'Asia/Shanghai',
    population: 1408500,
  },
  {
    name: 'South Tangerang',
    region: 'Banten',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -6.2886,
    longitude: 106.7179,
    timezone: 'Asia/Jakarta',
    population: 1404785,
  },
  {
    name: 'San Diego',
    region: 'California',
    country: 'United States',
    countryCode: 'US',
    latitude: 32.7157,
    longitude: -117.1647,
    timezone: 'America/Los_Angeles',
    population: 1404452,
  },
  {
    name: 'Zhanjiang',
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 21.2339,
    longitude: 110.3875,
    timezone: 'Asia/Shanghai',
    population: 1400709,
  },
  {
    name: 'Fushun',
    region: 'Liaoning',
    country: 'China',
    countryCode: 'CN',
    latitude: 41.8867,
    longitude: 123.9436,
    timezone: 'Asia/Shanghai',
    population: 1400646,
  },
  {
    name: 'Gwangju',
    region: 'Gwangju',
    country: 'South Korea',
    countryCode: 'KR',
    latitude: 35.1547,
    longitude: 126.9156,
    timezone: 'Asia/Seoul',
    population: 1398538,
  },
  {
    name: 'Rajkot',
    region: 'Gujarat',
    country: 'India',
    countryCode: 'IN',
    latitude: 22.2916,
    longitude: 70.7932,
    timezone: 'Asia/Kolkata',
    population: 1390640,
  },
  {
    name: 'Luoyang',
    region: 'Henan',
    country: 'China',
    countryCode: 'CN',
    latitude: 34.6735,
    longitude: 112.4368,
    timezone: 'Asia/Shanghai',
    population: 1390581,
  },
  {
    name: 'Guadalajara',
    region: 'Jalisco',
    country: 'Mexico',
    countryCode: 'MX',
    latitude: 20.6774,
    longitude: -103.3475,
    timezone: 'America/Mexico_City',
    population: 1385629,
  },
  {
    name: 'Bronx',
    region: 'New York',
    country: 'United States',
    countryCode: 'US',
    latitude: 40.8499,
    longitude: -73.8664,
    timezone: 'America/New_York',
    population: 1385108,
  },
  {
    name: 'Guankou',
    region: 'Hunan',
    country: 'China',
    countryCode: 'CN',
    latitude: 28.1586,
    longitude: 113.6271,
    timezone: 'Asia/Shanghai',
    population: 1380000,
  },
  {
    name: 'Huế',
    region: 'Thừa Thiên Huế Province',
    country: 'Vietnam',
    countryCode: 'VN',
    latitude: 16.4619,
    longitude: 107.5955,
    timezone: 'Asia/Bangkok',
    population: 1380000,
  },
  {
    name: 'Milan',
    region: 'Lombardy',
    country: 'Italy',
    countryCode: 'IT',
    latitude: 45.4643,
    longitude: 9.1895,
    timezone: 'Europe/Rome',
    population: 1371498,
  },
  {
    name: 'Najafgarh',
    region: 'Delhi',
    country: 'India',
    countryCode: 'IN',
    latitude: 28.6092,
    longitude: 76.9798,
    timezone: 'Asia/Kolkata',
    population: 1365000,
  },
  {
    name: "N'Djamena",
    region: 'N’Djaména',
    country: 'Chad',
    countryCode: 'TD',
    latitude: 12.1067,
    longitude: 15.0444,
    timezone: 'Africa/Ndjamena',
    population: 1359526,
  },
  {
    name: 'Handan',
    region: 'Hebei',
    country: 'China',
    countryCode: 'CN',
    latitude: 36.61,
    longitude: 114.4876,
    timezone: 'Asia/Shanghai',
    population: 1358318,
  },
  {
    name: 'Bannu',
    region: 'Khyber Pakhtunkhwa',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 32.9853,
    longitude: 70.604,
    timezone: 'Asia/Karachi',
    population: 1357890,
  },
  {
    name: 'Yichang',
    region: 'Hubei',
    country: 'China',
    countryCode: 'CN',
    latitude: 30.7144,
    longitude: 111.2847,
    timezone: 'Asia/Shanghai',
    population: 1350150,
  },
  {
    name: 'Antananarivo',
    region: 'Analamanga',
    country: 'Madagascar',
    countryCode: 'MG',
    latitude: -18.9137,
    longitude: 47.5361,
    timezone: 'Indian/Antananarivo',
    population: 1349501,
  },
  {
    name: 'Heze',
    region: 'Shandong',
    country: 'China',
    countryCode: 'CN',
    latitude: 35.2393,
    longitude: 115.4736,
    timezone: 'Asia/Shanghai',
    population: 1346717,
  },
  {
    name: 'Antalya',
    region: 'Antalya',
    country: 'Türkiye',
    countryCode: 'TR',
    latitude: 36.9081,
    longitude: 30.6956,
    timezone: 'Europe/Istanbul',
    population: 1344000,
  },
  {
    name: 'Abobo',
    region: 'Abidjan Autonomous District',
    country: 'Ivory Coast',
    countryCode: 'CI',
    latitude: 5.4161,
    longitude: -4.0159,
    timezone: 'Africa/Abidjan',
    population: 1340083,
  },
  {
    name: 'Jamshedpur',
    region: 'Jharkhand',
    country: 'India',
    countryCode: 'IN',
    latitude: 22.8028,
    longitude: 86.1855,
    timezone: 'Asia/Kolkata',
    population: 1339438,
  },
  {
    name: 'Douala',
    region: 'Littoral',
    country: 'Cameroon',
    countryCode: 'CM',
    latitude: 4.0483,
    longitude: 9.7043,
    timezone: 'Africa/Douala',
    population: 1338082,
  },
  {
    name: 'Basra',
    region: 'Basra',
    country: 'Iraq',
    countryCode: 'IQ',
    latitude: 30.5085,
    longitude: 47.7804,
    timezone: 'Asia/Baghdad',
    population: 1326564,
  },
  {
    name: 'Dallas',
    region: 'Texas',
    country: 'United States',
    countryCode: 'US',
    latitude: 32.7831,
    longitude: -96.8067,
    timezone: 'America/Chicago',
    population: 1326087,
  },
  {
    name: 'Saitama',
    region: 'Saitama',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 35.9081,
    longitude: 139.6566,
    timezone: 'Asia/Tokyo',
    population: 1324854,
  },
  {
    name: 'Gorakhpur',
    region: 'Haryana',
    country: 'India',
    countryCode: 'IN',
    latitude: 29.4477,
    longitude: 75.6721,
    timezone: 'Asia/Kolkata',
    population: 1324570,
  },
  {
    name: 'Niamey',
    region: 'Niamey',
    country: 'Niger',
    countryCode: 'NE',
    latitude: 13.5137,
    longitude: 2.1098,
    timezone: 'Africa/Niamey',
    population: 1323691,
  },
  {
    name: 'Liupanshui',
    region: 'Guizhou',
    country: 'China',
    countryCode: 'CN',
    latitude: 26.5944,
    longitude: 104.8333,
    timezone: 'Asia/Shanghai',
    population: 1320825,
  },
  {
    name: 'Taguig',
    region: 'National Capital Region',
    country: 'Philippines',
    countryCode: 'PH',
    latitude: 14.5243,
    longitude: 121.0792,
    timezone: 'Asia/Manila',
    population: 1308085,
  },
  {
    name: 'Maoming',
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 21.6663,
    longitude: 110.9136,
    timezone: 'Asia/Shanghai',
    population: 1307802,
  },
  {
    name: 'Calgary',
    region: 'Alberta',
    country: 'Canada',
    countryCode: 'CA',
    latitude: 51.0501,
    longitude: -114.0853,
    timezone: 'America/Edmonton',
    population: 1306784,
  },
  {
    name: 'Tripoli',
    region: 'Tripoli',
    country: 'Libya',
    countryCode: 'LY',
    latitude: 32.8874,
    longitude: 13.1873,
    timezone: 'Africa/Tripoli',
    population: 1302947,
  },
  {
    name: 'Medina',
    region: 'Medina Region',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    latitude: 24.4686,
    longitude: 39.6142,
    timezone: 'Asia/Riyadh',
    population: 1300000,
  },
  {
    name: 'Callao',
    region: 'Callao',
    country: 'Peru',
    countryCode: 'PE',
    latitude: -12.0516,
    longitude: -77.1345,
    timezone: 'America/Lima',
    population: 1300000,
  },
  {
    name: 'Yaoundé',
    region: 'Centre',
    country: 'Cameroon',
    countryCode: 'CM',
    latitude: 3.8667,
    longitude: 11.5167,
    timezone: 'Africa/Douala',
    population: 1299369,
  },
  {
    name: 'Qinzhou',
    region: 'Guangxi',
    country: 'China',
    countryCode: 'CN',
    latitude: 21.9825,
    longitude: 108.6506,
    timezone: 'Asia/Shanghai',
    population: 1296300,
  },
  {
    name: 'Luohe',
    region: 'Henan',
    country: 'China',
    countryCode: 'CN',
    latitude: 33.5639,
    longitude: 114.0427,
    timezone: 'Asia/Shanghai',
    population: 1294974,
  },
  {
    name: 'Xiangyang',
    region: 'Hubei',
    country: 'China',
    countryCode: 'CN',
    latitude: 32.0422,
    longitude: 112.1448,
    timezone: 'Asia/Shanghai',
    population: 1294733,
  },
  {
    name: 'Yangjiang',
    region: 'Guangdong',
    country: 'China',
    countryCode: 'CN',
    latitude: 21.8556,
    longitude: 111.9627,
    timezone: 'Asia/Shanghai',
    population: 1292987,
  },
  {
    name: 'Yixing',
    region: 'Jiangsu',
    country: 'China',
    countryCode: 'CN',
    latitude: 31.3606,
    longitude: 119.8202,
    timezone: 'Asia/Shanghai',
    population: 1285785,
  },
  {
    name: 'Pimpri',
    region: 'Maharashtra',
    country: 'India',
    countryCode: 'IN',
    latitude: 18.6229,
    longitude: 73.807,
    timezone: 'Asia/Kolkata',
    population: 1284606,
  },
  {
    name: 'Da Nang',
    region: 'Da Nang City',
    country: 'Vietnam',
    countryCode: 'VN',
    latitude: 16.0678,
    longitude: 108.2208,
    timezone: 'Asia/Ho_Chi_Minh',
    population: 1276000,
  },
  {
    name: 'Amman',
    region: 'Amman',
    country: 'Jordan',
    countryCode: 'JO',
    latitude: 31.9552,
    longitude: 35.945,
    timezone: 'Asia/Amman',
    population: 1275857,
  },
  {
    name: 'Budta',
    region: 'Autonomous Region in Muslim Mindanao',
    country: 'Philippines',
    countryCode: 'PH',
    latitude: 7.2042,
    longitude: 124.4397,
    timezone: 'Asia/Manila',
    population: 1273715,
  },
  {
    name: 'Belgrade',
    region: 'Central Serbia',
    country: 'Serbia',
    countryCode: 'RS',
    latitude: 44.804,
    longitude: 20.4651,
    timezone: 'Europe/Belgrade',
    population: 1273651,
  },
  {
    name: 'Biên Hòa',
    region: 'Dong Nai',
    country: 'Vietnam',
    countryCode: 'VN',
    latitude: 10.9447,
    longitude: 106.8243,
    timezone: 'Asia/Ho_Chi_Minh',
    population: 1272235,
  },
  {
    name: 'Montevideo',
    region: 'Montevideo Department',
    country: 'Uruguay',
    countryCode: 'UY',
    latitude: -34.9033,
    longitude: -56.1882,
    timezone: 'America/Montevideo',
    population: 1270737,
  },
  {
    name: 'Xuchang',
    region: 'Henan',
    country: 'China',
    countryCode: 'CN',
    latitude: 34.0319,
    longitude: 113.863,
    timezone: 'Asia/Shanghai',
    population: 1265536,
  },
  {
    name: 'Kalyān',
    region: 'Maharashtra',
    country: 'India',
    countryCode: 'IN',
    latitude: 19.2437,
    longitude: 73.1355,
    timezone: 'Asia/Kolkata',
    population: 1262255,
  },
  {
    name: 'Zigong',
    region: 'Sichuan',
    country: 'China',
    countryCode: 'CN',
    latitude: 29.3416,
    longitude: 104.7769,
    timezone: 'Asia/Shanghai',
    population: 1262064,
  },
] as const;
